### ISSUE TITLE
'variable' and 'tensor' have incompatible tensor type

### ISSUE THREAD

**Issue by yiling-chen** [dvlab-research/LLaMA-VID#4] opened 2023-12-05 04:07 UTC
Hi,

When trying to run CLI inference, I ran into the following error. Do you have any idea of how to fix it? Thanks.

> Traceback (most recent call last):
  File "/home/yilche/miniconda3/envs/llama-vid/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yilche/miniconda3/envs/llama-vid/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/data-2/LLaMA-VID/llamavid/serve/cli.py", line 137, in <module>
    main(args)
  File "/mnt/data-2/LLaMA-VID/llamavid/serve/cli.py", line 39, in main
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, args.load_8bit, args.load_4bit)
  File "/mnt/data-2/Projects/Florence-Video/code/Labelers/LLaMA-VID/llamavid/model/builder.py", line 98, in load_pretrained_model
    model.get_model().initialize_attention_modules(model.config, for_eval=True)
  File "/mnt/data-2/Projects/Florence-Video/code/Labelers/LLaMA-VID/llamavid/model/llamavid_arch.py", line 178, in initialize_attention_modules
    self.vlm_att_query.data = self.vlm_att_query.data.to(device=device_type, dtype=weight_type)
RuntimeError: Attempted to call 'variable.set_data(tensor)', but 'variable' and 'tensor' have incompatible tensor type.

**Comment by yanwei-li** [comment] 2023-12-05 06:59
Hi, could you please provide the running commend? I tested the raw float16, int8, and int4 types, but did not reproduce this error.

**Comment by yiling-chen** [comment] 2023-12-05 19:02
The command was just llike
`python -m llamavid.serve.cli --model-path /path/to/llama-vid/llama-vid-7b-full-224-video-fps-1/ --image-file test.mp4`

I manually downloaded the model weights and put them as the instructions.

My conda env is as follows:

```
# packages in environment at /home/yilche/miniconda3/envs/llama-vid:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
accelerate                0.21.0                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohttp                   3.9.1                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.2.0                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
bitsandbytes              0.41.0                   pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2023.08.22           h06a4308_0
certifi                   2023.11.17               pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
chatunivi                 1.0.1                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cmake                     3.27.9                   pypi_0    pypi
contourpy                 1.2.0                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
decord                    0.6.0                    pypi_0    pypi
deepspeed                 0.9.5                    pypi_0    pypi
distro                    1.8.0                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.6.1                    pypi_0    pypi
einops-exts               0.0.4                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
fairscale                 0.4.13                   pypi_0    pypi
fastapi                   0.104.1                  pypi_0    pypi
ffmpy                     0.3.1                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
fonttools                 4.46.0                   pypi_0    pypi
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.12.0                pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.40                   pypi_0    pypi
gradio                    3.35.2                   pypi_0    pypi
gradio-client             0.2.9                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hjson                     3.1.0                    pypi_0    pypi
httpcore                  0.17.3                   pypi_0    pypi
httpx                     0.24.0                   pypi_0    pypi
huggingface-hub           0.19.4                   pypi_0    pypi
idna                      3.6                      pypi_0    pypi
imageio                   2.31.3                   pypi_0    pypi
imageio-ffmpeg            0.4.9                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jsonlines                 4.0.0                    pypi_0    pypi
jsonschema                4.20.0                   pypi_0    pypi
jsonschema-specifications 2023.11.2                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
libuuid                   1.41.5               h5eee18b_0
linkify-it-py             2.0.2                    pypi_0    pypi
lit                       17.0.6                   pypi_0    pypi
llamavid                  1.0                      pypi_0    pypi
llava                     1.1.1                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markdown2                 2.4.11                   pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.8.2                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
networkx                  3.2.1                    pypi_0    pypi
ninja                     1.11.1.1                 pypi_0    pypi
numpy                     1.26.2                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
openai                    1.3.7                    pypi_0    pypi
openssl                   3.0.12               h7f8727e_0
orjson                    3.9.10                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.1.3                    pypi_0    pypi
peft                      0.4.0                    pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.1          py310h06a4308_0
protobuf                  4.25.1                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pydantic                  1.10.13                  pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.10.13              h955ad1f_0
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
referencing               0.31.1                   pypi_0    pypi
regex                     2023.10.3                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rpds-py                   0.13.2                   pypi_0    pypi
safetensors               0.4.1                    pypi_0    pypi
scikit-learn              1.2.2                    pypi_0    pypi
scipy                     1.11.4                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentencepiece             0.1.99                   pypi_0    pypi
sentry-sdk                1.38.0                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                68.0.0          py310h06a4308_0
shortuuid                 1.0.11                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
starlette                 0.27.0                   pypi_0    pypi
svgwrite                  1.4.3                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
timm                      0.6.13                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenizers                0.13.3                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.0.1                    pypi_0    pypi
torchvision               0.15.2                   pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
transformers              4.31.0                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
urllib3                   2.1.0                    pypi_0    pypi
uvicorn                   0.24.0.post1             pypi_0    pypi
wandb                     0.16.0                   pypi_0    pypi
wavedrom                  2.0.3.post3              pypi_0    pypi
websockets                12.0                     pypi_0    pypi
wheel                     0.41.2          py310h06a4308_0
xz                        5.4.5                h5eee18b_0
yarl                      1.9.3                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
```

Also tested to download the model directly from huggingface. Same error.

**Comment by yanwei-li** [comment] 2023-12-06 06:56
Hi Yiling, I'm not sure if this error was fixed in the previous code update, because I cannot reproduce such an error. Would you mind pulling the code and trying this again?
```
CUDA_VISIBLE_DEVICES=0 python -m llamavid.serve.cli --model-path /path/to/llama-vid/llama-vid-7b-full-224-video-fps-1/ --image-file test.mp4
```

**Comment by yanwei-li** [comment] 2023-12-09 15:35
Close it now, please reopen it if you have further questions.

**Closed by yanwei-li** 2023-12-09 15:35 UTC
